modLoader = "javafml"
loaderVersion = "[${loaderVersion},)"
license = "LGPL-3.0"

[[mods]]
modId = "moremcmeta_animation_plugin"
version = "${modVersion}"
displayName = "MoreMcmeta Animation Plugin"
authors = "soir20"
description = '''
Default plugin for MoreMcmeta that animates textures.
'''

[[dependencies.moremcmeta_animation_plugin]]
modId = "moremcmeta"
mandatory = true
versionRange = "[${minMoreMcmetaVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.moremcmeta_animation_plugin]]
modId = "forge"
mandatory = true
versionRange = "[${loaderVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moremcmeta_animation_plugin]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"